name: Create Pull Request

on:
  push:
    branches:
      - master

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: 305017
          private_key: f3b4769d6bc749246b534e94807c4bd2fc94c2c1
     
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.1.2
        with:                 
          token: ${{ steps.generate-token.outputs.token }}
          branch: dev
          title: Automated Pull Request
          body: Automated Pull Request
