name: Create Pull Request

on:
  push:
    branches:
      - master

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
     
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.1.2
        with:                 
          token: ${{ steps.generate-token.outputs.token }}
          branch: dev
          title: Automated Pull Request
          body: Automated Pull Request
